global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: voxelmarket-backend1
    metrics_path: /metrics
    static_configs:
      - targets:
          - api:3000

  - job_name: voxelmarket-backend2
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend2:3002

  - job_name: voxelmarket-backend3
    metrics_path: /metrics
    static_configs:
      - targets:
          - backend3:3003

  - job_name: voxelmarket-mysql
    metrics_path: /metrics
    static_configs:
      - targets:
          - mysql-exporter:9104